### ISSUE TITLE
dcr --explain / ERROR: The file "sites/all/modules/custom" does not exist.

### ISSUE THREAD

**Issue by Decipher** [alexdesignworks/dcr#14]
When I run the `dcr --explain` command I get the resulting error:

```
ERROR: The file "sites/all/modules/custom" does not exist.
```

**Comment by Decipher** [comment]
Looks like the `--explain` part is irrelevant, assuming that if `dcr` is run without a specific target it assumes that you want to run it in `sites/all/modules/custom`.

**Comment by alexdesignworks** [comment]
@Decipher yes, this is by design. I agree that those targets are not the best options - open to suggestions.

But the functionality to run `dcr` without targets cannot be changed. I.e., if you run `dcr` without targets it will use settings in `.dcr.yml`.

Open to suggestions to make the whole workflow better.

**Comment by alexdesignworks** [comment]
Closing until better workflow is proposed
